---
title: "Assignment 1: Introduction"
author: "Nadia Barbo"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project"


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I used R in undergrad to do statistical analysis for my lab work (I was in a herpetology lab). I am also using R in my current lab to do data analyes on zebrafish behavior (for my MP). I took ENVIRON 710, so I have experience using R in that context. The data analysis using R that I have previously mentioned are my only experiences with data analytics. I don't have previous experience using Git but I have used GitHub Desktop is John's GIS Data Analytics class.

2. Are there any components of the course about which you feel confident?

> Answer: I feel confident with R basics - such as coding dos and don'ts, basic commands, and how the interface is set up. I know how to make scatterplots, box plots, and bar graphs and how to customize them to be visually appealing. I am also comfortable with some pretty general statistical analyses (like finding summary statistics from a clean dataset).

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel apprehensive about cleaning data. I have tried to clean excel data many times and it never goes as planned. I'm also really excited to learn how to do this properly, however, because I know it will save me a lot of time. I'm also a little nervous about the final project because when it comes to data analytics, I have a hard time knowing where to start. But that is why I'm taking this course and hopefully I will feel more confident by the time I start the final project!


## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/nadiabarbo/EDA-Spring2023

## 4) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
